spring:
  datasource:
    username: phonebook_local
    password: tiger
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: oracle 
  data:
    jpa:
      repositories:
        enabled: true

      
server:
  servlet:
    context-path: /PhoneBook
  port: 8082
